import { Navbar } from '../../components/layout/Navbar';
import { Footer } from '../../components/layout/Footer';
import Link from 'next/link';

export const metadata = { title: 'About VocaBrawl — The Arena of Letters' };

const SECTIONS = [
  {
    emoji: '🎯', title: 'What is VocaBrawl?',
    content: `VocaBrawl is a high-octane real-time competitive word-solving platform. Think VocaWord — but instead of a solo daily puzzle, you're matched against a real human opponent, and the clock is ticking. Both players receive the same secret 5-letter word, and the first to crack it in fewer guesses wins.`,
  },
  {
    emoji: '🔐', title: 'Anti-Cheat Architecture',
    content: `The secret word never leaves the server. Your browser never possesses it. When you submit a guess, the server evaluates it and sends back only the colour result array — not the word. This "headless" architecture makes cheating structurally impossible, not just policy-prohibited.`,
  },
  {
    emoji: '⚡', title: 'HPC Low-Latency Engine',
    content: `The game server is optimised for ultra-low latency: WebSocket connections skip HTTP polling for direct upgrading, message compression is disabled for speed, guess evaluation uses bitmask operations and typed arrays, and object pooling reduces garbage collection pressure. Every millisecond counts when two players are neck-and-neck.`,
  },
  {
    emoji: '📊', title: 'ELO Rating System',
    content: `VocaBrawl uses the standard chess ELO formula (K=32). Win against a higher-rated player and you gain more points. Lose to a lower-rated player and you lose more. Your rank reflects true skill — not just hours played. Tiers range from Scribe (starter) → Scholar → Lexicon → Sage → Grandmaster → Oracle.`,
  },
  {
    emoji: '🎨', title: 'How to Read the Tiles',
    content: 'Green (correct): the letter is in the correct position. Yellow (present): the letter is in the word but in the wrong position. Gray (absent): the letter is not in the word at all. Your keyboard updates to reflect these states, helping you eliminate possibilities faster.',
  },
  {
    emoji: '🏃', title: 'The Gauntlet Mode',
    content: `Solo PvE. No opponent needed. Start with 60 seconds and solve as many words as you can. Each solved word adds 15 bonus seconds to your clock. Each word solved in fewer guesses scores more points. Run out of guesses on a word and it\'s game over. Perfect for practice or when you just want to brawl alone.`,
  },
];

const FAQS = [
  { q: 'Is the game fair?', a: 'Yes — both players receive the exact same word generated by the server at match-start using a cryptographically seeded random selection.' },
  { q: 'Can I cheat by inspecting network traffic?', a: 'No. The secret word is never transmitted to the client. Only colour-coded result arrays are sent back, making it impossible to extract the word from network data.' },
  { q: 'What dictionaries are used?', a: 'A curated list of 500+ common 5-letter English words — similar in style to the original VocaWord list. Obscure words are intentionally excluded to keep matches fair and fun.' },
  { q: 'How is ELO calculated?', a: 'Standard chess ELO: K-factor of 32. Expected score is computed from rating difference, and actual outcome (1 for win, 0 for loss) is compared against it. Both players\' ratings update immediately after match completion.' },
  { q: 'Do I need to log in for The Gauntlet?', a: 'No! Gauntlet is available without registration. However, your score won\'t be saved to the leaderboard. Create an account to track your progress.' },
];

export default function AboutPage() {
  return (
    <div className="min-h-screen flex flex-col">
      <Navbar />
      <main style={{ flex: 1, padding: '48px 24px', maxWidth: 860, margin: '0 auto', width: '100%' }}>

        <h1 className="font-hand" style={{ fontSize: 'clamp(2.2rem, 8vw, 3.2rem)', fontWeight: 700, color: 'var(--wb-ink)', marginBottom: 8 }}>
          About VocaBrawl ✏️
        </h1>
        <p style={{ color: 'var(--wb-ink-light)', fontSize: '1.05rem', marginBottom: 48 }}>
          Everything you need to know about the arena, the rules, and the technology behind it.
        </p>

        {/* Sections */}
        <div style={{ display: 'flex', flexDirection: 'column', gap: 32 }}>
          {SECTIONS.map(s => (
            <div key={s.title} className="wb-card" style={{ padding: 'clamp(20px, 5vw, 32px)' }}>
              <h2 className="font-hand" style={{ fontSize: '1.9rem', fontWeight: 700, color: 'var(--wb-ink)', marginBottom: 12 }}>
                {s.emoji} {s.title}
              </h2>
              <p style={{ color: 'var(--wb-ink-light)', lineHeight: 1.75, fontSize: '0.97rem' }}>{s.content}</p>
            </div>
          ))}
        </div>

        <hr className="wb-divider" style={{ margin: '48px 0' }} />

        {/* Tile Legend */}
        <h2 className="font-hand" style={{ fontSize: '2rem', fontWeight: 700, color: 'var(--wb-ink)', marginBottom: 24 }}>🎨 Tile Colour Guide</h2>
        <div style={{ display: 'flex', gap: 20, flexWrap: 'wrap', marginBottom: 48 }}>
          {[
            { state: 'correct', letter: 'A', label: 'Correct position', color: 'var(--wb-correct)' },
            { state: 'present', letter: 'R', label: 'Wrong position',   color: 'var(--wb-present)' },
            { state: 'absent',  letter: 'X', label: 'Not in word',      color: 'var(--wb-absent)' },
          ].map(t => (
            <div key={t.state} className="wb-card" style={{ padding: '20px 28px', display: 'flex', alignItems: 'center', gap: 16, flex: '1 1 200px' }}>
              <div className={`wb-tile ${t.state}`}>{t.letter}</div>
              <div>
                <p className="font-hand" style={{ fontSize: '1.2rem', fontWeight: 700, color: t.color }}>{t.label}</p>
                <p style={{ fontSize: '0.85rem', color: 'var(--wb-ink-faint)' }}>State: {t.state}</p>
              </div>
            </div>
          ))}
        </div>

        {/* ELO Tiers */}
        <h2 className="font-hand" style={{ fontSize: '2rem', fontWeight: 700, color: 'var(--wb-ink)', marginBottom: 24 }}>📊 ELO Tier System</h2>
        <div className="wb-card" style={{ overflow: 'hidden', marginBottom: 48 }}>
          {[
            { tier: '✏️ Scribe',       range: '0 – 999',    color: 'var(--wb-ink-light)' },
            { tier: '🥇 Scholar',      range: '1000 – 1199', color: 'var(--wb-correct)' },
            { tier: '⚡ Lexicon',      range: '1200 – 1399', color: '#EA580C' },
            { tier: '💎 Sage',         range: '1400 – 1599', color: 'var(--wb-blue)' },
            { tier: '🔮 Grandmaster',  range: '1600 – 1799', color: '#7C3AED' },
            { tier: '👑 Oracle',       range: '1800+',        color: 'var(--wb-purple)' },
          ].map((t, i) => (
            <div key={t.tier} style={{ display: 'flex', justifyContent: 'space-between', padding: '12px 24px', borderBottom: i < 5 ? '1.5px solid var(--wb-grid)' : 'none', background: i % 2 === 0 ? 'white' : 'var(--wb-paper-alt)' }}>
              <span className="font-hand" style={{ fontSize: '1.2rem', fontWeight: 700, color: t.color }}>{t.tier}</span>
              <span className="font-hand" style={{ fontSize: '1.1rem', color: 'var(--wb-ink-light)' }}>{t.range} ELO</span>
            </div>
          ))}
        </div>

        {/* FAQ */}
        <h2 className="font-hand" style={{ fontSize: '2rem', fontWeight: 700, color: 'var(--wb-ink)', marginBottom: 24 }}>❓ FAQ</h2>
        <div style={{ display: 'flex', flexDirection: 'column', gap: 16, marginBottom: 48 }}>
          {FAQS.map(faq => (
            <div key={faq.q} className="wb-card" style={{ padding: 'clamp(16px, 4vw, 28px)' }}>
              <p className="font-hand" style={{ fontSize: '1.2rem', fontWeight: 700, color: 'var(--wb-ink)', marginBottom: 8 }}>Q: {faq.q}</p>
              <p style={{ color: 'var(--wb-ink-light)', fontSize: '0.95rem', lineHeight: 1.7 }}>A: {faq.a}</p>
            </div>
          ))}
        </div>

        <div style={{ textAlign: 'center' }}>
          <Link href="/"><button className="wb-btn wb-btn-primary wb-btn-lg">⚔️ Enter the Arena</button></Link>
        </div>
      </main>
      <Footer />
    </div>
  );
}

